//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LXNavi.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LXNavi.Resources.Localization.StringResource", typeof(StringResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Accelerometer 的本地化字符串。
        /// </summary>
        internal static string Accelerometer {
            get {
                return ResourceManager.GetString("Accelerometer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Blue 的本地化字符串。
        /// </summary>
        internal static string Blue {
            get {
                return ResourceManager.GetString("Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All data records will be cleared. Do you want to continue? 的本地化字符串。
        /// </summary>
        internal static string ClearingDataMessage {
            get {
                return ResourceManager.GetString("ClearingDataMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current Location 的本地化字符串。
        /// </summary>
        internal static string CurrentLocation {
            get {
                return ResourceManager.GetString("CurrentLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All data records have been cleared. 的本地化字符串。
        /// </summary>
        internal static string DataClearedMessage {
            get {
                return ResourceManager.GetString("DataClearedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Done 的本地化字符串。
        /// </summary>
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Green 的本地化字符串。
        /// </summary>
        internal static string Green {
            get {
                return ResourceManager.GetString("Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gyroscope 的本地化字符串。
        /// </summary>
        internal static string Gyroscope {
            get {
                return ResourceManager.GetString("Gyroscope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Keep Centered 的本地化字符串。
        /// </summary>
        internal static string KeepCentered {
            get {
                return ResourceManager.GetString("KeepCentered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Languages 的本地化字符串。
        /// </summary>
        internal static string Languages {
            get {
                return ResourceManager.GetString("Languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The location service is disabled. Please check the location service switch and permissions. 的本地化字符串。
        /// </summary>
        internal static string LocationDisabledMessage {
            get {
                return ResourceManager.GetString("LocationDisabledMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Magnetometer 的本地化字符串。
        /// </summary>
        internal static string Magnetometer {
            get {
                return ResourceManager.GetString("Magnetometer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please start monitoring first. 的本地化字符串。
        /// </summary>
        internal static string MonitoringNotStartedMessage {
            get {
                return ResourceManager.GetString("MonitoringNotStartedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to connect to the network, map may not load properly. 的本地化字符串。
        /// </summary>
        internal static string NetworkDisabledMessage {
            get {
                return ResourceManager.GetString("NetworkDisabledMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No 的本地化字符串。
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No Data 的本地化字符串。
        /// </summary>
        internal static string NoData {
            get {
                return ResourceManager.GetString("NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to obtain your current location through GNSS or network. Please try again later. 的本地化字符串。
        /// </summary>
        internal static string NullLocationMessage {
            get {
                return ResourceManager.GetString("NullLocationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ok 的本地化字符串。
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Options 的本地化字符串。
        /// </summary>
        internal static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Red 的本地化字符串。
        /// </summary>
        internal static string Red {
            get {
                return ResourceManager.GetString("Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sensors 的本地化字符串。
        /// </summary>
        internal static string Sensors {
            get {
                return ResourceManager.GetString("Sensors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 These sensors are not supported:{0}. 的本地化字符串。
        /// </summary>
        internal static string SensorsNotSupportedMessage {
            get {
                return ResourceManager.GetString("SensorsNotSupportedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start Monitoring 的本地化字符串。
        /// </summary>
        internal static string StartMonitoring {
            get {
                return ResourceManager.GetString("StartMonitoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start Plotting 的本地化字符串。
        /// </summary>
        internal static string StartTrack {
            get {
                return ResourceManager.GetString("StartTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 StepLength 的本地化字符串。
        /// </summary>
        internal static string StepLength {
            get {
                return ResourceManager.GetString("StepLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stop 的本地化字符串。
        /// </summary>
        internal static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Track 的本地化字符串。
        /// </summary>
        internal static string Track {
            get {
                return ResourceManager.GetString("Track", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Track Color 的本地化字符串。
        /// </summary>
        internal static string TrackColor {
            get {
                return ResourceManager.GetString("TrackColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please stop track plotting first. 的本地化字符串。
        /// </summary>
        internal static string TrackPlottingNotStopMessage {
            get {
                return ResourceManager.GetString("TrackPlottingNotStopMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UTC 的本地化字符串。
        /// </summary>
        internal static string Utc {
            get {
                return ResourceManager.GetString("Utc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Yellow 的本地化字符串。
        /// </summary>
        internal static string Yellow {
            get {
                return ResourceManager.GetString("Yellow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Yes 的本地化字符串。
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
